import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './scss/index.scss'

import { Fira_Code } from 'next/font/google'
const firaCode = Fira_Code({subsets:['latin']})


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={firaCode.className}>
        {children}
      </body>
    </html>
  )
}
